os:
  - linux
  - osx
sudo: false

language: ruby
rvm:
  - 2.6.0


script:
  - rspec testing -f d
  - ruby -e "puts \"Files found by glob: #{Dir.glob('testing/rspec/spec/**/*_spec.rb')}\""
  - rspec --pattern testing/rspec/spec/**/*_spec.rb -f d
